### ISSUE TITLE
get termonad compiling with GHC 8.6

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/termonad#97]
Right now termonad only compiles with GHC 8.4 on Stackage LTS-12.

It would be nice to have support for compiling with GHC 8.6 (and Stackage LTS-13) as well.  If you get this working, I'll make a release and we can get Termonad back in Stackage.

If you want to tackle this issue and you're a nix user, it would also be nice if you could update the nix stuff to use a more recent version of nixpkgs (a recent one that compiles all the Haskell packages with ghc-8.6 by default).

**Comment by clinty** [comment]
For reference, the build fails with:

```
src/Termonad/Config/Vec.hs:541:26: error:
    • Cannot apply expression of type ‘Sing w0’
      to a visible type argument ‘ns’
    • In the first argument of ‘fmapSingMatrix’, namely ‘(sing @_ @ns)’
      In the expression: fmapSingMatrix (sing @_ @ns)
      In an equation for ‘fmap’: fmap = fmapSingMatrix (sing @_ @ns)
    |
541 |   fmap = fmapSingMatrix (sing @_ @ns)
    |                          ^^^^^^^^^^^

src/Termonad/Config/Vec.hs:545:61: error:
    • Cannot apply expression of type ‘Sing w0’
      to a visible type argument ‘ns’
    • In the first argument of ‘toListMatrix’, namely ‘(sing @_ @ns)’
      In the second argument of ‘(.)’, namely
        ‘toListMatrix (sing @_ @ns)’
      In the expression:
        Data.Foldable.foldr comb b . toListMatrix (sing @_ @ns)
    |
545 |   foldr comb b = Data.Foldable.foldr comb b . toListMatrix (sing @_ @ns)
    |                                                             ^^^^^^^^^^^
```

**Comment by clinty** [comment]
Not sure if this is the right fix, but it builds.
