### ISSUE TITLE
not possible build with ghc-8.8.x

### ISSUE THREAD

**Issue by mimi1vx** [cdepillabout/termonad#142]
ghc-8.8.x changed work with `fail`

```
[ 4 of 15] Compiling Termonad.Gtk     ( src/Termonad/Gtk.hs, /home/mimi/git.public/termonad/dist-newstyle/build/x86_64-linux/ghc-8.8.1/termonad-3.0.0.0/build/Termonad/Gtk.o )

src/Termonad/Gtk.hs:49:16: error:
    • Variable not in scope: fail :: [Char] -> m Application
    • Perhaps you meant ‘tail’ (imported from Termonad.Prelude)
   |
49 |     Nothing -> fail "Could not create application for some reason!"
   |                ^^^^

```

**Comment by cdepillabout** [comment]
Thanks for bringing this up.

This should actually just throw an exception.  This could use [`throwIO`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#v:throwIO) and [`userError`](http://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO-Error.html#v:userError).

Although this also appears to be what `fail` does for the `IO` monad, so maybe just importing `fail` so it is in scope would be the easiest thing here.

**Comment by cdepillabout** [comment]
This has been fixed in #145.
